version: "3.8"

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: "rabbitmq"
    ports:
      - "5672:5672"    # RabbitMQ communication port
      - "15672:15672"  # RabbitMQ web UI
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  mongodb:
    image: "mongo"
    container_name: "mongodb"
    ports:
      - "27017:27017"  # MongoDB database port

  user-service:
    build: ./user-service
    container_name: "user-service"
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
      - mongodb

  notification-service:
    build: ./notification-service
    container_name: "notification-service"
    depends_on:
      - rabbitmq
      - mongodb
